don't fail if no tests were collected

diff --git a/.github/workflows/pytest.yml b/.github/workflows/pytest.yml
--- a/.github/workflows/pytest.yml
+++ b/.github/workflows/pytest.yml
@@ -116,7 +116,16 @@ jobs:
           sudo mv nf-test /usr/local/bin/
 
       - name: Test with pytest
-        run: python3 -m pytest tests/${{matrix.test}} --color=yes --cov-report=xml --cov-config=.github/.coveragerc --cov=nf_core
+        run: |
+          python3 -m pytest tests/${{matrix.test}} --color=yes --cov-report=xml --cov-config=.github/.coveragerc --cov=nf_core
+          # don't fail if no tests were collected, e.g. for test_licence.py
+          if [ "${exit_code}" -eq 5 ]; then
+            echo "No tests were collected"
+            exit 0
+          elif [ "${exit_code}" -ne 0 ]; then
+            echo "Tests failed with exit code ${exit_code}"
+            exit 1
+          fi
 
       - uses: codecov/codecov-action@v1
         name: Upload code coverage report
